### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by Cathella** [Cathella/Apple_Homepage_Clone#1]
Review of the apple clone page layout

**Comment by ricardo123321** [comment]
don't forget to put text-decoration on the links

**Comment by ricardo123321** [comment]
activate the stickler on this project

**Comment by LoboArkano** [comment]
Use header tag for your h1 and h2.

**Comment by hemantso** [comment]
include action attribute in the form element

**Comment by ricardo123321** [comment]
ad the play button after the "word's story"
